<script setup lang="ts">
/**
 * BlockIcon – Einzelnes Lucide-Icon.
 *
 * Alle Icons werden statisch importiert (kein defineAsyncComponent),
 * damit SSR und Client identisch rendern (kein Hydration-Mismatch).
 * Bei unbekanntem iconName wird das Star-Icon als Fallback genutzt.
 */
import type { Component } from 'vue'
import type { IconBlock } from '~/types/funnel'
import {
  Star,
  Heart,
  Check,
  Phone,
  Mail,
  Calendar,
  User,
  Settings,
  Zap,
  Rocket,
  Activity,
  BarChart2,
  Wrench,
  Clock,
  MapPin,
  Briefcase,
  ThumbsUp,
  ThumbsDown,
  Gift,
  Home,
  Laptop,
  Globe,
  Shield,
  Lock,
  Unlock,
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Plus,
  Minus,
  X,
  Search,
  Edit,
  Trash,
  Download,
  Upload,
  Share,
  Eye,
  EyeOff,
  Bell,
  BellOff,
  Bookmark,
  Tag,
  Flag,
  Image,
  Video,
  Music,
  File,
  Folder,
  Link,
  ExternalLink,
  Copy,
  Clipboard,
  MessageCircle,
  MessageSquare,
  Send,
  Smile,
  Frown,
  Meh,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Thermometer,
  Map,
  Navigation,
  Compass,
  Car,
  Truck,
  Plane,
  Train,
  Coffee,
  Pizza,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Package,
  Toolbox,
  Scissors,
  Pen,
  PenTool,
  Sliders,
  Filter,
  Layout,
  Grid,
  List,
  Table,
  Layers,
  Cpu,
  Database,
  Server,
  Wifi,
  Bluetooth,
  Battery,
  Power,
  Monitor,
  Smartphone,
  Tablet,
  Printer,
  Camera,
  Headphones,
  Mic,
  Volume2,
  VolumeX,
  Play,
  Pause,
  StopCircle,
  SkipForward,
  SkipBack,
  Repeat,
  Shuffle,
  Award,
  Trophy,
  Target,
  Crosshair,
  Anchor,
  Aperture,
  Box,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
} from 'lucide-vue-next'

/** Statische Map: iconName (lowercase oder kebab-case) -> Lucide-Komponente. */
const iconMap: Record<string, Component> = {
  star: Star,
  heart: Heart,
  check: Check,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  user: User,
  settings: Settings,
  gear: Settings,
  zap: Zap,
  lightning: Zap,
  rocket: Rocket,
  activity: Activity,
  'bar-chart': BarChart2,
  'bar-chart-2': BarChart2,
  chart: BarChart2,
  wrench: Wrench,
  tool: Toolbox,
  tools: Wrench,
  toolbox: Toolbox,
  clock: Clock,
  'map-pin': MapPin,
  location: MapPin,
  briefcase: Briefcase,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  gift: Gift,
  home: Home,
  laptop: Laptop,
  globe: Globe,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  info: Info,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  plus: Plus,
  minus: Minus,
  x: X,
  close: X,
  search: Search,
  edit: Edit,
  trash: Trash,
  delete: Trash,
  download: Download,
  upload: Upload,
  share: Share,
  eye: Eye,
  'eye-off': EyeOff,
  bell: Bell,
  'bell-off': BellOff,
  bookmark: Bookmark,
  tag: Tag,
  flag: Flag,
  image: Image,
  video: Video,
  music: Music,
  file: File,
  folder: Folder,
  link: Link,
  'external-link': ExternalLink,
  copy: Copy,
  clipboard: Clipboard,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  send: Send,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  rain: CloudRain,
  wind: Wind,
  thermometer: Thermometer,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  car: Car,
  truck: Truck,
  plane: Plane,
  train: Train,
  coffee: Coffee,
  pizza: Pizza,
  'shopping-cart': ShoppingCart,
  cart: ShoppingCart,
  'shopping-bag': ShoppingBag,
  bag: ShoppingBag,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  money: DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  package: Package,
  scissors: Scissors,
  pen: Pen,
  'pen-tool': PenTool,
  sliders: Sliders,
  filter: Filter,
  layout: Layout,
  grid: Grid,
  list: List,
  table: Table,
  layers: Layers,
  cpu: Cpu,
  database: Database,
  server: Server,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  power: Power,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  printer: Printer,
  camera: Camera,
  headphones: Headphones,
  mic: Mic,
  volume: Volume2,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  mute: VolumeX,
  play: Play,
  pause: Pause,
  stop: StopCircle,
  'skip-forward': SkipForward,
  'skip-back': SkipBack,
  repeat: Repeat,
  shuffle: Shuffle,
  award: Award,
  trophy: Trophy,
  target: Target,
  crosshair: Crosshair,
  anchor: Anchor,
  aperture: Aperture,
  box: Box,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  diamond: Diamond,
}

const props = defineProps<{
  block: IconBlock
  mode: 'editor' | 'live'
}>()

/** Aufgeloeste Icon-Komponente oder Fallback (Star). */
const resolvedIcon = computed<Component>(() => {
  const key = props.block.iconName?.toLowerCase().trim() ?? ''
  return iconMap[key] ?? Star
})

/** Icongroesse in Pixeln (Standard: 32). */
const iconSize = computed(() => props.block.size ?? 32)

/** Farbe aus block.styles.color oder CSS-Variable. */
const iconColor = computed(() => props.block.styles?.color ?? 'var(--funnel-text)')
</script>

<template>
  <!--
    Rein dekoratives Icon. aria-hidden="true" damit Screenreader es ueberspringen.
    Soll das Icon eine semantische Bedeutung haben, muss der Block-Nutzer
    einen begleitenden Textblock mit der Bedeutung hinzufuegen.
  -->
  <div
    class="flex w-full justify-center"
    :style="block.styles?.textAlign ? `text-align: ${block.styles.textAlign}` : undefined"
  >
    <component
      :is="resolvedIcon"
      :size="iconSize"
      :color="iconColor"
      :stroke-width="1.75"
      aria-hidden="true"
    />
  </div>
</template>
